Update setup.py
trouble with original 
 
       /tmp/pip-install-71ibfqbk/hydrate-spf_a75c233c00634ddd9c14f63b59a3681c/setup.py:13: DeprecationWarning: Due to possible ambiguity, 'convert()' is deprecated. Use 'convert_file()'  or 'convert_text()'.
        description = pypandoc.convert('README.md', 'rst')
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-71ibfqbk/hydrate-spf_a75c233c00634ddd9c14f63b59a3681c/setup.py", line 13, in <module>
          description = pypandoc.convert('README.md', 'rst')
        File "/home/linuxbrew/.linuxbrew/opt/python@3.10/lib/python3.10/site-packages/pypandoc/__init__.py", line 66, in convert
          raise RuntimeError("Format missing, but need one (identified source as text as no "
      RuntimeError: Format missing, but need one (identified source as text as no file with that name was found).